//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public int hid { get; set; }
        public int cid { get; set; }
        public int rating { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string comment1 { get; set; }
        public string date { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual User User { get; set; }
    }
}
