//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYR.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Hotel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Please Enter the Hotel Name")]
        [RegularExpression(@"^[a-zA-Z''-'\s]{1,40}$",
      ErrorMessage = "Numbers and special characters are not allowed in the last name.")]
        public string name { get; set; }
        [Required(ErrorMessage = "Please Enter the Description")]
        public string description { get; set; }
        [Required(ErrorMessage = "Please Enter the Price Range")]
        public string MaxPrice { get; set; }
        [Required(ErrorMessage = "Please Enter the City")]
        public string city { get; set; }
        [Required(ErrorMessage = "Please Enter the Address")]
        public string address { get; set; }
        [Required(ErrorMessage = "Please Enter the Phone Number")]
        public string phoneNumber { get; set; }
        [Required(ErrorMessage = "Please Enter the faxNo")]
        public string faxNo { get; set; }
        [Required(ErrorMessage = "Please Enter the Rating")]
        public int adminRating { get; set; }
        public string picturePath { get; set; }
    }
}