//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYR.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please Enter the First Name")]
        [RegularExpression(@"^[a-zA-Z''-'\s]{1,40}$",
      ErrorMessage = "Numbers and special characters are not allowed in the last name.")]
        public string firstName { get; set; }
        [Required(ErrorMessage = "Please Enter the Last Name")]
        [RegularExpression(@"^[a-zA-Z''-'\s]{1,40}$",
      ErrorMessage = "Numbers and special characters are not allowed in the last name.")]
        public string lastName { get; set; }
        [Required(ErrorMessage = "Please Enter the User Name")]
        public string username { get; set; }
        [Required(ErrorMessage = "Please Enter the Email Name")]
        [DataType(DataType.EmailAddress, ErrorMessage = "This must be a valid email address")]
        public string email { get; set; }
        [Required(ErrorMessage = "Please Enter the Password Name")]
  
        public string password { get; set; }

        [Required(ErrorMessage = "Please Enter the Secret Question")]
        public string secQ { get; set; }
        [Required(ErrorMessage = "Please Enter the Secret Answer")]
        public string secA { get; set; }

        public string profilePic { get; set; }
        public string status { get; set; }
        public string type { get; set; }
        [Required(ErrorMessage = "Please Enter Age")]
        [Range(1, 100, ErrorMessage = "This must not be greater than 100")]
        public Nullable<int> age { get; set; }
    }
}

